export const capitalizationProperNouns = {
  africa: 'Africa',
  april: 'April',
  asia: 'Asia',
  australia: 'Australia',
  berlin: 'Berlin',
  california: 'California',
  canada: 'Canada',
  december: 'December',
  delhi: 'Delhi',
  dublin: 'Dublin',
  february: 'February',
  christmas: 'Christmas',
  english: 'English',
  europe: 'Europe',
  france: 'France',
  friday: 'Friday',
  germany: 'Germany',
  india: 'India',
  ireland: 'Ireland',
  italy: 'Italy',
  january: 'January',
  japan: 'Japan',
  july: 'July',
  june: 'June',
  london: 'London',
  madrid: 'Madrid',
  mexico: 'Mexico',
  monday: 'Monday',
  nasa: 'NASA',
  november: 'November',
  october: 'October',
  paris: 'Paris',
  rome: 'Rome',
  saturday: 'Saturday',
  seattle: 'Seattle',
  september: 'September',
  sunday: 'Sunday',
  sydney: 'Sydney',
  thanksgiving: 'Thanksgiving',
  thursday: 'Thursday',
  tokyo: 'Tokyo',
  tuesday: 'Tuesday',
  typescript: 'TypeScript',
  wednesday: 'Wednesday',
} as const

export const capitalizationBrandNames = {
  adobe: 'Adobe',
  android: 'Android',
  bitbucket: 'Bitbucket',
  chatgpt: 'ChatGPT',
  docker: 'Docker',
  firefox: 'Firefox',
  gitlab: 'GitLab',
  gmail: 'Gmail',
  github: 'GitHub',
  iphone: 'iPhone',
  instagram: 'Instagram',
  ios: 'iOS',
  ipad: 'iPad',
  javascript: 'JavaScript',
  jira: 'Jira',
  kubernetes: 'Kubernetes',
  linkedin: 'LinkedIn',
  linux: 'Linux',
  macbook: 'MacBook',
  macos: 'macOS',
  mongodb: 'MongoDB',
  npm: 'npm',
  openai: 'OpenAI',
  photoshop: 'Photoshop',
  popos: 'Pop!_OS',
  postgres: 'Postgres',
  postgresql: 'PostgreSQL',
  salesforce: 'Salesforce',
  react: 'React',
  shopify: 'Shopify',
  whatsapp: 'WhatsApp',
  wordpress: 'WordPress',
  youtube: 'YouTube',
  zoom: 'Zoom',
} as const

export const capitalizationAcronyms = [
  'ACL',
  'AES',
  'AI',
  'ANSI',
  'API',
  'ARM',
  'ASCII',
  'BIOS',
  'CD',
  'CDN',
  'CI',
  'CLI',
  'CMS',
  'CSS',
  'CSV',
  'CPU',
  'DHCP',
  'DNS',
  'HTTP',
  'HTTPS',
  'ETL',
  'IDE',
  'FAQ',
  'FTP',
  'GPU',
  'GUID',
  'IAM',
  'ICMP',
  'IEEE',
  'IETF',
  'IMAP',
  'IP',
  'IRC',
  'ISO',
  'IT',
  'EU',
  'HTML',
  'JPEG',
  'JSON',
  'JPG',
  'JWT',
  'LAN',
  'LDAP',
  'LLM',
  'MFA',
  'ML',
  'NASA',
  'OCR',
  'OEM',
  'OS',
  'OTP',
  'PDF',
  'PCI',
  'PNG',
  'QA',
  'QR',
  'RAM',
  'REST',
  'RPC',
  'RSA',
  'SDK',
  'SEO',
  'SMTP',
  'SNMP',
  'SOAP',
  'SQL',
  'SSH',
  'SSL',
  'SVG',
  'TCP',
  'TLS',
  'TTL',
  'UK',
  'UI',
  'UDP',
  'URI',
  'URL',
  'US',
  'USB',
  'UUID',
  'UX',
  'XML',
] as const

export const capitalizationTitlePhrases = {
  'lord of the rings': 'Lord of the Rings',
  'the great gatsby': 'The Great Gatsby',
  'to kill a mockingbird': 'To Kill a Mockingbird',
  'united kingdom': 'United Kingdom',
} as const

export const contextSensitiveCapitalizationTerms = [
  { word: 'march', replacement: 'March' },
  { word: 'may', replacement: 'May' },
  { word: 'august', replacement: 'August' },
] as const
