export interface CompoundPhrasePattern {
  phrase: string
  replacement: string
  message: string
}

export interface ContextualCompoundModifierPattern
  extends CompoundPhrasePattern {
  allowedFollowingWords?: string[]
}

export const hyphenatedCompoundPatterns: CompoundPhrasePattern[] = [
  {
    phrase: 'decision making process',
    replacement: 'decision-making process',
    message: 'Use a hyphen in the compound modifier "decision-making".',
  },
  {
    phrase: 'high quality report',
    replacement: 'high-quality report',
    message: 'Use a hyphen in the compound modifier "high-quality".',
  },
]

export const missingHyphenPatterns: CompoundPhrasePattern[] = [
  {
    phrase: 'cross functional team',
    replacement: 'cross-functional team',
    message: 'Use a hyphen in "cross-functional" before a noun.',
  },
  {
    phrase: 'full time role',
    replacement: 'full-time role',
    message: 'Use a hyphen in "full-time" before a noun.',
  },
  {
    phrase: 'part time role',
    replacement: 'part-time role',
    message: 'Use a hyphen in "part-time" before a noun.',
  },
  {
    phrase: 'up to date guide',
    replacement: 'up-to-date guide',
    message: 'Use a hyphen in "up-to-date" before a noun.',
  },
  {
    phrase: 'well known author',
    replacement: 'well-known author',
    message: 'Use a hyphen in "well-known" before a noun.',
  },
  {
    phrase: 'user friendly guide',
    replacement: 'user-friendly guide',
    message: 'Use a hyphen in "user-friendly" before a noun.',
  },
]

export const unnecessaryHyphenPatterns: CompoundPhrasePattern[] = [
  {
    phrase: 'co-worker',
    replacement: 'coworker',
    message: 'Remove the hyphen from "coworker".',
  },
  {
    phrase: 'e-mail',
    replacement: 'email',
    message: 'Use the closed compound "email".',
  },
  {
    phrase: 'web-site',
    replacement: 'website',
    message: 'Use the closed compound "website".',
  },
  {
    phrase: 'code-base',
    replacement: 'codebase',
    message: 'Use the closed compound "codebase".',
  },
  {
    phrase: 'log-in',
    replacement: 'login',
    message: 'Use the noun form "login" here.',
  },
  {
    phrase: 'work-flow',
    replacement: 'workflow',
    message: 'Use the closed compound "workflow".',
  },
]

export const contextualModifierHyphenPatterns: ContextualCompoundModifierPattern[] =
  [
    {
      phrase: 'command line',
      replacement: 'command-line',
      message: 'Use a hyphen in "command-line" before a noun.',
      allowedFollowingWords: [
        'argument',
        'arguments',
        'experience',
        'experiences',
        'flag',
        'flags',
        'interface',
        'interfaces',
        'option',
        'options',
        'parser',
        'parsers',
        'tool',
        'tools',
        'workflow',
        'workflows',
      ],
    },
    {
      phrase: 'client side',
      replacement: 'client-side',
      message: 'Use a hyphen in "client-side" before a noun.',
      allowedFollowingWords: [
        'code',
        'logic',
        'rendering',
        'routing',
        'script',
        'scripts',
        'validation',
      ],
    },
    {
      phrase: 'cross platform',
      replacement: 'cross-platform',
      message: 'Use a hyphen in "cross-platform" before a noun.',
      allowedFollowingWords: [
        'app',
        'apps',
        'build',
        'builds',
        'component',
        'components',
        'experience',
        'experiences',
        'support',
        'tool',
        'tools',
      ],
    },
    {
      phrase: 'end to end',
      replacement: 'end-to-end',
      message: 'Use hyphens in "end-to-end" before a noun.',
      allowedFollowingWords: [
        'checks',
        'coverage',
        'demo',
        'demos',
        'flow',
        'flows',
        'guide',
        'guides',
        'pipeline',
        'pipelines',
        'process',
        'processes',
        'support',
        'test',
        'tests',
        'workflow',
        'workflows',
      ],
    },
    {
      phrase: 'large scale',
      replacement: 'large-scale',
      message: 'Use hyphens in "large-scale" before a noun.',
      allowedFollowingWords: [
        'migration',
        'migrations',
        'release',
        'releases',
        'rollout',
        'rollouts',
        'test',
        'tests',
        'update',
        'updates',
      ],
    },
    {
      phrase: 'long term',
      replacement: 'long-term',
      message: 'Use hyphens in "long-term" before a noun.',
      allowedFollowingWords: [
        'goal',
        'goals',
        'maintenance',
        'plan',
        'plans',
        'roadmap',
        'roadmaps',
        'strategy',
        'support',
      ],
    },
    {
      phrase: 'mobile first',
      replacement: 'mobile-first',
      message: 'Use a hyphen in "mobile-first" before a noun.',
      allowedFollowingWords: [
        'approach',
        'design',
        'experience',
        'layout',
        'strategy',
        'workflow',
      ],
    },
    {
      phrase: 'open source',
      replacement: 'open-source',
      message: 'Use a hyphen in "open-source" before a noun.',
      allowedFollowingWords: [
        'community',
        'communities',
        'component',
        'components',
        'contributor',
        'contributors',
        'framework',
        'frameworks',
        'library',
        'libraries',
        'maintainer',
        'maintainers',
        'package',
        'packages',
        'project',
        'projects',
        'software',
        'tool',
        'tools',
      ],
    },
    {
      phrase: 'real time',
      replacement: 'real-time',
      message: 'Use hyphens in "real-time" before a noun.',
      allowedFollowingWords: [
        'alerts',
        'analytics',
        'feedback',
        'preview',
        'previews',
        'status',
        'sync',
        'telemetry',
        'updates',
        'validation',
        'view',
        'views',
      ],
    },
    {
      phrase: 'server side',
      replacement: 'server-side',
      message: 'Use a hyphen in "server-side" before a noun.',
      allowedFollowingWords: [
        'code',
        'component',
        'components',
        'logic',
        'rendering',
        'validation',
      ],
    },
    {
      phrase: 'short term',
      replacement: 'short-term',
      message: 'Use hyphens in "short-term" before a noun.',
      allowedFollowingWords: [
        'fix',
        'fixes',
        'goal',
        'goals',
        'plan',
        'plans',
        'roadmap',
        'roadmaps',
        'workaround',
        'workarounds',
      ],
    },
    {
      phrase: 'small scale',
      replacement: 'small-scale',
      message: 'Use hyphens in "small-scale" before a noun.',
      allowedFollowingWords: [
        'experiment',
        'experiments',
        'pilot',
        'pilots',
        'release',
        'releases',
        'rollout',
        'rollouts',
        'test',
        'tests',
        'trial',
        'trials',
      ],
    },
    {
      phrase: 'state of the art',
      replacement: 'state-of-the-art',
      message: 'Use hyphens in "state-of-the-art" before a noun.',
      allowedFollowingWords: [
        'editor',
        'editors',
        'model',
        'models',
        'pipeline',
        'pipelines',
        'platform',
        'platforms',
        'system',
        'systems',
        'tool',
        'tools',
        'workflow',
        'workflows',
      ],
    },
    {
      phrase: 'step by step',
      replacement: 'step-by-step',
      message: 'Use hyphens in "step-by-step" before a noun.',
      allowedFollowingWords: [
        'example',
        'examples',
        'flow',
        'flows',
        'guide',
        'guides',
        'instructions',
        'migration',
        'migrations',
        'process',
        'processes',
        'tutorial',
        'tutorials',
        'walkthrough',
        'walkthroughs',
      ],
    },
    {
      phrase: 'user friendly',
      replacement: 'user-friendly',
      message: 'Use a hyphen in "user-friendly" before a noun.',
      allowedFollowingWords: [
        'api',
        'apis',
        'copy',
        'dashboard',
        'dashboards',
        'editor',
        'editors',
        'experience',
        'experiences',
        'interface',
        'interfaces',
        'message',
        'messages',
        'tool',
        'tools',
        'workflow',
        'workflows',
      ],
    },
  ]
